import {useState} from 'react'
import { type NextPage } from "next";
import Head from "next/head";

import {Input} from "~/component/input"
import { FormGroup } from "~/component/FormGroup";
import {Button} from "~/component/Button"

import { api } from '~/utils/api';
import { sign } from 'crypto';
import { signIn, signOut, useSession } from 'next-auth/react';


const GeneratePage: NextPage = () => {
  const [form, setForm] = useState({
    prompt: "",
  });

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data){
      console.log("mutation finished", data);
    }
  })

  function handleFormSubmit(e: React.FormEvent){
    e.preventDefault();
    // TODO: submit the form data to the backend 
    generateIcon.mutate({
      prompt: form.prompt
    })
  }

 
  function updateForm(key: string){
    return function(e: React.ChangeEvent<HTMLInputElement>){
      setForm ((prev) => ({
        ...prev,
        [key]: e.target.value,
      }))
    }
  }

  const session = useSession();

  const isLoggedIn = !!session.data;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {!isLoggedIn && 
        <Button onClick={()=> {
          signIn().catch(console.error)
          }}>
            Login
            </Button>
          }
          {isLoggedIn && 
        <Button onClick={()=> {
          signOut().catch(console.error)
          }}>
            Logout
            </Button>
          }
          {session.data?.user.name}
        <form className="flex flex-col gap-4" 
        onSubmit={handleFormSubmit}
        >
            <FormGroup>
            <label>Prompt</label>
              <Input
                value={form.prompt}
                onChange ={updateForm("prompt")}>
              </Input>
            </FormGroup>
            <button className= "bg-blue-400 px-4 py-2 rounded hover:bg-blue-500">Submit</button>
        </form>       
      </main>
    </>
  );
};

export default GeneratePage;

