import { type NextPage } from "next";
import Head from "next/head";
import Image from 'next/image'

import { PrimaryLinkButton } from "~/component/PrimaryLinkButton";

function HeroBanner(){
  return (
    <section className="gap-12 mb-24 grid grid-cols-1 sm:grid-cols-2 px-8 mt-12 sm:mt-24 ">
      <div className="flex flex-col gap-4">
      <h1 className="text-6xl">Generate Icons With A Click Of A Button</h1>
      <p className="text-2xl">Empower Your Creativity: Harness AI to Craft Iconic Designs Instantly, Effortlessly!</p>
      <PrimaryLinkButton href="/generate" className="self-start"> Generate Your Icons</PrimaryLinkButton>
      </div>
      <Image src="/banner.png"
        alt="an image of a bunch of icons"
        width="400"
        height="300"
        className="order-first sm:-order-none"
      />
     
    </section>
  )
}


const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen">
        <HeroBanner/>
      </main>
    </>
  );
};

export default HomePage;